
INSERT INTO prompt (prompt_id, prompt_category, prompt_body)
VALUES
(gen_random_uuid(), 'Entertainment', 'Discuss the impact of streaming services on traditional cable TV.'),
(gen_random_uuid(), 'Entertainment', 'Who is your favorite actor or actress and why?'),
(gen_random_uuid(), 'Entertainment', 'Review the latest movie you watched.'),
(gen_random_uuid(), 'Entertainment', 'What is your favorite TV show and what makes it special?'),
(gen_random_uuid(), 'Entertainment', 'How has the music industry changed with the rise of digital platforms?'),
(gen_random_uuid(), 'Entertainment', 'Which book would you like to see adapted into a movie and why?'),
(gen_random_uuid(), 'Entertainment', 'Discuss the cultural significance of video games in modern society.'),
(gen_random_uuid(), 'Entertainment', 'What are your thoughts on the influence of social media celebrities?'),
(gen_random_uuid(), 'Entertainment', 'How do you think virtual reality will change the future of entertainment?'),
(gen_random_uuid(), 'Entertainment', 'What is your favorite concert experience and why?'),
(gen_random_uuid(), 'Fashion', 'What are the latest fashion trends for this season?'),
(gen_random_uuid(), 'Fashion', 'How has streetwear influenced high fashion?'),
(gen_random_uuid(), 'Fashion', 'Who is your favorite fashion designer and why?'),
(gen_random_uuid(), 'Fashion', 'What role does sustainability play in the fashion industry today?'),
(gen_random_uuid(), 'Fashion', 'How do cultural influences shape fashion trends?'),
(gen_random_uuid(), 'Fashion', 'What are some essential pieces for a minimalist wardrobe?'),
(gen_random_uuid(), 'Fashion', 'Discuss the impact of fast fashion on the environment.'),
(gen_random_uuid(), 'Fashion', 'How can technology be integrated into fashion design?'),
(gen_random_uuid(), 'Fashion', 'What is your favorite fashion era and why?'),
(gen_random_uuid(), 'Fashion', 'How do you see the future of fashion evolving?'),
(gen_random_uuid(), 'Food', 'What is your favorite cuisine and why?'),
(gen_random_uuid(), 'Food', 'Share a recipe for your favorite dish.'),
(gen_random_uuid(), 'Food', 'How has the rise of food delivery apps changed the restaurant industry?'),
(gen_random_uuid(), 'Food', 'Discuss the benefits of a plant-based diet.'),
(gen_random_uuid(), 'Food', 'What are some traditional dishes from your culture?'),
(gen_random_uuid(), 'Food', 'How do you think climate change is affecting food production?'),
(gen_random_uuid(), 'Food', 'What are your thoughts on genetically modified organisms (GMOs) in food?'),
(gen_random_uuid(), 'Food', 'How can people reduce food waste in their daily lives?'),
(gen_random_uuid(), 'Food', 'What are some of the best street foods you have tried?'),
(gen_random_uuid(), 'Food', 'How has social media influenced food trends?'),
(gen_random_uuid(), 'Health', 'What are some effective ways to manage stress?'),
(gen_random_uuid(), 'Health', 'Discuss the importance of mental health awareness.'),
(gen_random_uuid(), 'Health', 'How can regular exercise improve your overall health?'),
(gen_random_uuid(), 'Health', 'What are the benefits of a balanced diet?'),
(gen_random_uuid(), 'Health', 'How does sleep affect your physical and mental health?'),
(gen_random_uuid(), 'Health', 'What are some natural remedies for common illnesses?'),
(gen_random_uuid(), 'Health', 'Discuss the impact of technology on healthcare.'),
(gen_random_uuid(), 'Health', 'What are the benefits and risks of taking dietary supplements?'),
(gen_random_uuid(), 'Health', 'How can mindfulness and meditation improve well-being?'),
(gen_random_uuid(), 'Health', 'What role does genetics play in personal health?'),
(gen_random_uuid(), 'Technology', 'How has artificial intelligence changed various industries?'),
(gen_random_uuid(), 'Technology', 'What are the potential benefits and risks of self-driving cars?'),
(gen_random_uuid(), 'Technology', 'Discuss the impact of social media on society.'),
(gen_random_uuid(), 'Technology', 'How can blockchain technology be used beyond cryptocurrencies?'),
(gen_random_uuid(), 'Technology', 'What are the implications of 5G technology?'),
(gen_random_uuid(), 'Technology', 'How do you think wearable technology will evolve in the future?'),
(gen_random_uuid(), 'Technology', 'What are the pros and cons of remote work enabled by technology?'),
(gen_random_uuid(), 'Technology', 'How is technology transforming education?'),
(gen_random_uuid(), 'Technology', 'What are some ethical considerations surrounding data privacy?'),
(gen_random_uuid(), 'Technology', 'How can technology help address climate change?'),
(gen_random_uuid(), 'Travel', 'What is your favorite travel destination and why?'),
(gen_random_uuid(), 'Travel', 'Share your best travel tips for budget-conscious travelers.'),
(gen_random_uuid(), 'Travel', 'How has the COVID-19 pandemic changed the way people travel?'),
(gen_random_uuid(), 'Travel', 'What are the benefits of solo travel?'),
(gen_random_uuid(), 'Travel', 'Discuss the impact of tourism on local cultures and economies.'),
(gen_random_uuid(), 'Travel', 'What are some must-have items for any traveler?'),
(gen_random_uuid(), 'Travel', 'How can travelers be more environmentally conscious?'),
(gen_random_uuid(), 'Travel', 'What are some hidden gems you have discovered while traveling?'),
(gen_random_uuid(), 'Travel', 'How do you prepare for a long-haul flight?'),
(gen_random_uuid(), 'Travel', 'What are the top destinations on your travel bucket list?');

INSERT INTO profile (profile_id, profile_activation_token, profile_bio, profile_date_created, profile_email,
                     profile_full_name, profile_image, profile_hash, profile_username)
values (gen_random_uuid(), '1234567890abcdef1234567890abcdef', 'Im a full-stack developer', now(),'smendez22@cnm.edu',
        'Monica Mendez', 'https://example.com/avatar.jpg', '1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef1','myblahblah');


INSERT INTO post (post_id, post_body, post_date_created, post_image, post_title, profile_id, prompt_id),
    VALUES (gen_random_uuid(), 'This is a post body', now(), 'https://example.com/image.jpg', 'This is a post title',);